services:
  gateway:
    enabled: true
    replicas: 2
    image: ghcr.io/bryant2305/gateway:latest
    port: 3333
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  auth:
    enabled: true
    replicas: 2
    image: ghcr.io/bryant2305/auth:latest
    port: 3010
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  user:
    enabled: true
    replicas: 2
    image: ghcr.io/bryant2305/user:latest
    port: 3000
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  property:
    enabled: true
    replicas: 2
    image: ghcr.io/bryant2305/property:latest
    port: 3003
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  reservation:
    enabled: true
    replicas: 2
    image: ghcr.io/bryant2305/reservation:latest
    port: 3004
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  mail:
    enabled: true
    replicas: 1
    image: ghcr.io/bryant2305/mail:latest
    port: 3006
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"