---
# Namespace template
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.environment }}
    app: renthub
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
